DATA:
  ROOT: 'datasets/rsv'
  DATASET: 'rsv'
  BASE_SIZE: 520
  CROP_SIZE: 480

SOLVER:
  STEPS: [9000, 15000]
  MAX_ITER: 17000

MODEL:
  WEIGHT: 'work_dirs/pretrained/encnet_jpu_resnet101_pcontext_trimed.pth'
  BACKBONE: 'resnet101'
  JPU: True

OUTPUT_DIR: 'work_dirs/rsv'